name: ariadne-mac
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - pip
  - qiskit>=1.0
  - qiskit-aer>=0.13
  - openqasm3
  - mitiq>=0.33
  - stim>=1.12
  - mqt.qcec>=1.6
  - mqt.ddsim>=1.8
  - quimb>=1.6.3
  - cotengra>=0.7
  - opt_einsum>=3.3
  - numpy>=1.26
  - scipy>=1.11
  - networkx>=3.2
  - rich>=13.7
  - typer>=0.12
  - pytest>=8.0
  - mypy>=1.10
  - ruff>=0.5
  - qualtran>=0.2
  - azure-quantum=1.*
  - pip:
      - jax>=0.4; platform_system=='Darwin' and platform_machine=='arm64'
      - jaxlib>=0.4; platform_system=='Darwin' and platform_machine=='arm64'
      - jax-metal>=0.1; platform_system=='Darwin' and platform_machine=='arm64'

