name: ✨ Feature Request
description: Suggest a new feature for Ariadne
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We love hearing ideas from the community.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Currently, Ariadne doesn't support routing to IBM Quantum cloud services...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: |
        Add a new backend that interfaces with IBM Quantum via Qiskit Runtime...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: |
        - Using Qiskit directly (but loses routing intelligence)
        - Building a custom wrapper (too much work)

  - type: textarea
    id: api-example
    attributes:
      label: Example API Usage
      description: How would users interact with this feature?
      value: |
        ```python
        from ariadne import QuantumRouter
        
        router = QuantumRouter()
        # Your proposed API here
        ```

  - type: dropdown
    id: impact
    attributes:
      label: Expected Impact
      description: How many users would benefit?
      options:
        - Most users would benefit
        - Many users would benefit
        - Some users would benefit
        - Niche use case
    validations:
      required: true

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Changes
      description: Would this require breaking changes?
      options:
        - No breaking changes
        - Minor breaking changes
        - Major breaking changes
        - Not sure
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Any thoughts on how to implement this?
      placeholder: |
        Could extend the BackendSelector class to include cloud backends...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I am willing to help implement this feature
          required: false
        - label: I have searched for similar feature requests
          required: true