mem_cap_gib: 24
sv:
  max_qubits_fp32: 31
  max_qubits_fp64: 29
tn:
  treewidth_threshold: 12
  min_depth: 4
dd:
  enable: true
  max_qubits: 40
  redundancy_threshold: 0.20  # fraction of repeated two-qubit interactions
routing_order: [clifford_stim, sv_if_fits, dd_if_redundant, tn_else]
notes: |
  - Prefer Stim for purely Clifford circuits.
  - Prefer SV when it fits in memory (fp32 then fp64) and n is modest.
  - Prefer DD when many repeated interactions suggest compression.
  - Otherwise prefer TN if treewidth is small; else TN with slicing.

