# file generated by setuptools_scm
# don't change, don't track in version control

from typing import TYPE_CHECKING

__all__ = [
    "__version__",
    "__version_tuple__",
    "version",
    "version_tuple",
    "__commit_id__",
    "commit_id",
]

if TYPE_CHECKING:
    VERSION_TUPLE = tuple[int | str, ...]
else:
    VERSION_TUPLE = object

version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE

__version__ = version = "0.2.0"
__version_tuple__ = version_tuple = (0, 2, 0)

__commit_id__ = commit_id = "g33c8441"
